# Generated by Django 4.1.1 on 2022-10-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_department_role_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hire_date',
            new_name='defending',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='dribbling',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dept',
            new_name='pace',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='bonus',
            new_name='passing',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone',
            new_name='physical',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='shooting',
        ),
        migrations.AddField(
            model_name='employee',
            name='club',
            field=models.CharField(default=45, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='nation',
            field=models.CharField(default='france', max_length=100),
            preserve_default=False,
        ),
    ]
