# Generated by Django 4.1.1 on 2022-10-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_hire_date_employee_defending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='defending',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dribbling',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pace',
            field=models.IntegerField(default=0),
        ),
    ]
