# Generated by Django 4.1.1 on 2022-10-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_employee_defending_alter_employee_dribbling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='defending',
            field=models.IntegerField(default=0),
        ),
    ]
